# Generated by Django 2.0.2 on 2019-08-16 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20190816_1003'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='index',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
