# Generated by Django 2.0.13 on 2019-09-08 11:57

import datetime
from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_address_index'),
    ]

    operations = [
        migrations.CreateModel(
            name='AddressContactDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_person_name', models.TextField(blank=True, null=True)),
                ('contact_person_phone', models.CharField(blank=True, max_length=500, null=True)),
                ('contact_person_email', models.EmailField(blank=True, max_length=254, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='BusinessDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.TextField(blank=True, null=True)),
                ('business_tin', models.TextField(blank=True, null=True)),
                ('business_registration_number', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Documents',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.TextField(blank=True, null=True)),
                ('document_url', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SellerDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seller_id', models.CharField(blank=True, max_length=500, null=True, unique=True)),
                ('seller_status', models.CharField(blank=True, max_length=500, null=True)),
                ('name_on_id', models.TextField(blank=True, null=True)),
                ('id_type', models.TextField(blank=True, null=True)),
                ('upload_id_front_url', models.TextField(blank=True, null=True)),
                ('upload_id_back_url', models.TextField(blank=True, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone', models.TextField(blank=True, null=True)),
                ('has_agreed_to_terms', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='ShopDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shop_name', models.TextField(blank=True, null=True)),
                ('holiday_mode', models.BooleanField(default=False)),
                ('start_date', models.DateField(blank=True, default=datetime.datetime.now, null=True)),
                ('start_time', models.TimeField(blank=True, default=datetime.datetime.now, null=True)),
                ('end_date', models.DateField(blank=True, default=datetime.datetime.now, null=True)),
                ('end_time', models.TimeField(blank=True, default=datetime.datetime.now, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='address',
            name='index',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='dti',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='permit',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='sec',
        ),
        migrations.AddField(
            model_name='address',
            name='brgy',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='address',
            name='city',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='address',
            name='country',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='address',
            name='postal_code',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='address',
            name='region_state',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='address',
            name='street_bldg',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='pickup_address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='pickup_address', to='users.Address'),
        ),
        migrations.AddField(
            model_name='profile',
            name='return_address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='return_address', to='users.Address'),
        ),
        migrations.AddField(
            model_name='sellerdetails',
            name='shop_details',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.ShopDetails'),
        ),
        migrations.AddField(
            model_name='documents',
            name='profile',
            field=modelcluster.fields.ParentalKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='document', to='users.Profile'),
        ),
        migrations.AddField(
            model_name='businessdetails',
            name='business_address',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.Address'),
        ),
        migrations.AddField(
            model_name='address',
            name='contact_details',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.AddressContactDetails'),
        ),
        migrations.AddField(
            model_name='profile',
            name='business_details',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='users.BusinessDetails'),
        ),
        migrations.AddField(
            model_name='profile',
            name='seller_details',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.SellerDetails'),
        ),
    ]
