# Generated by Django 2.0.13 on 2019-09-15 08:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20190911_1517'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShippingInformation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userId', models.CharField(blank=True, max_length=500, null=True)),
                ('username', models.CharField(blank=True, max_length=500, null=True)),
                ('contact_person_phone', models.CharField(blank=True, max_length=500, null=True)),
                ('contact_person_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('label', models.CharField(blank=True, max_length=500, null=True)),
            ],
        ),
        migrations.RenameField(
            model_name='address',
            old_name='brgy',
            new_name='barangay',
        ),
        migrations.AddField(
            model_name='address',
            name='province',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='shippinginformation',
            name='address',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.Address'),
        ),
    ]
