# Generated by Django 2.0.2 on 2019-07-05 14:50

from django.db import migrations, models
import django.db.models.deletion
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_code', models.CharField(blank=True, max_length=500, null=True)),
                ('merchant_id', models.CharField(blank=True, max_length=500, null=True)),
                ('category_id', models.CharField(blank=True, max_length=500, null=True)),
                ('product_name', models.CharField(blank=True, max_length=500, null=True)),
                ('product_description', models.CharField(blank=True, max_length=500, null=True)),
                ('price', models.CharField(blank=True, max_length=500, null=True)),
                ('stock', models.CharField(blank=True, max_length=500, null=True)),
                ('product_weight', models.CharField(blank=True, max_length=500, null=True)),
                ('ship_out_in', models.CharField(blank=True, max_length=500, null=True)),
                ('parent_sku_reference_no', models.CharField(blank=True, max_length=500, null=True)),
                ('variation1_id', models.CharField(blank=True, max_length=500, null=True)),
                ('variation2_id', models.CharField(blank=True, max_length=500, null=True)),
                ('variation3_id', models.CharField(blank=True, max_length=500, null=True)),
                ('variation4_id', models.CharField(blank=True, max_length=500, null=True)),
                ('variation5_id', models.CharField(blank=True, max_length=500, null=True)),
                ('variation6_id', models.CharField(blank=True, max_length=500, null=True)),
                ('variation7_id', models.CharField(blank=True, max_length=500, null=True)),
                ('image1', models.CharField(blank=True, max_length=500, null=True)),
                ('image2', models.CharField(blank=True, max_length=500, null=True)),
                ('image3', models.CharField(blank=True, max_length=500, null=True)),
                ('image4', models.CharField(blank=True, max_length=500, null=True)),
                ('image5', models.CharField(blank=True, max_length=500, null=True)),
                ('image6', models.CharField(blank=True, max_length=500, null=True)),
                ('image7', models.CharField(blank=True, max_length=500, null=True)),
                ('other_logistics_provider_setting', models.CharField(blank=True, max_length=500, null=True)),
                ('other_logistics_provider_fee', models.CharField(blank=True, max_length=500, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProductPage',
            fields=[
                ('basepage_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='base.BasePage')),
                ('body', wagtail.core.fields.StreamField([('content', wagtail.core.blocks.RichTextBlock(icon='pilcrow')), ('image_block', wagtail.images.blocks.ImageChooserBlock(icon='image', label='Image Block'))], blank=True)),
            ],
            options={
                'abstract': False,
            },
            bases=('base.basepage',),
        ),
    ]
