# Generated by Django 2.0.13 on 2019-07-26 05:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='variations',
            name='image_upload',
            field=models.ForeignKey(blank=True, help_text='Optional: If you want to upload a new image. This will be used if Image URL is also present.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image'),
        ),
        migrations.AlterField(
            model_name='variations',
            name='image_url',
            field=models.CharField(blank=True, help_text='Optional: If your image is already hosted', max_length=2000, null=True),
        ),
    ]
