# Generated by Django 2.0.13 on 2019-09-17 17:06

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='order',
            name='product_ord_orderRe_a52d87_idx',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='additionalInfo',
            new_name='additional_info',
        ),
        migrations.RemoveField(
            model_name='order',
            name='orderReferenceNumber',
        ),
        migrations.AddField(
            model_name='order',
            name='id',
            field=models.AutoField(auto_created=True, default=django.utils.timezone.now, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='order_reference_number',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['order_reference_number'], name='product_ord_order_r_e5419e_idx'),
        ),
    ]
