# Generated by Django 2.0.13 on 2019-07-12 01:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailredirects', '0006_redirect_increase_max_length'),
        ('wagtailforms', '0003_capitalizeverbose'),
        ('wagtailmenus', '0022_auto_20170913_2125'),
        ('wagtailcore', '0040_page_draft_title'),
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productsimportpage',
            name='basepage_ptr',
        ),
        migrations.RemoveField(
            model_name='productspage',
            name='basepage_ptr',
        ),
        migrations.DeleteModel(
            name='ProductsImportPage',
        ),
        migrations.DeleteModel(
            name='ProductsPage',
        ),
    ]
