# Generated by Django 2.0.13 on 2019-07-29 05:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_auto_20190726_1322'),
    ]

    operations = [
        migrations.AddField(
            model_name='variations',
            name='image_url_from_sku',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='variations',
            name='image_upload',
            field=models.ForeignKey(blank=True, help_text='Optional: If you want to upload a new image. This will replace the image in the URL provided when bulk upload is performed.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image'),
        ),
    ]
