# Generated by Django 2.0.13 on 2019-07-12 01:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_productpage_productsimportpage_productspage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='order',
        ),
        migrations.DeleteModel(
            name='Order',
        ),
        migrations.DeleteModel(
            name='Product',
        ),
    ]
