# Generated by Django 2.0.2 on 2019-07-11 02:28

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailredirects', '0006_redirect_increase_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('base', '0001_initial'),
        ('wagtailmenus', '0022_auto_20170913_2125'),
        ('wagtailforms', '0003_capitalizeverbose'),
        ('contenttypes', '0002_remove_content_type_name'),
        ('wagtailcore', '0040_page_draft_title'),
        ('product', '0003_productspage'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProductImportPage',
            new_name='ProductsImportPage',
        ),
    ]
