# Generated by Django 2.0.2 on 2019-07-29 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_auto_20190729_1323'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='unpublished',
            field=models.BooleanField(default=False),
        ),
    ]
