# Generated by Django 2.0.2 on 2019-07-29 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_product_unpublished'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='stock_sum',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
