# Generated by Django 2.0.13 on 2019-07-12 01:13

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_auto_20190712_0913'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total', models.CharField(blank=True, max_length=500, null=True)),
                ('status', models.CharField(blank=True, max_length=500, null=True)),
                ('countdown', models.CharField(blank=True, max_length=500, null=True)),
                ('shipping_channel', models.CharField(blank=True, max_length=500, null=True)),
                ('creation_date', models.CharField(blank=True, max_length=500, null=True)),
                ('paid_date', models.CharField(blank=True, max_length=500, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_code', models.CharField(blank=True, max_length=500, null=True)),
                ('merchant_id', models.CharField(blank=True, max_length=500, null=True)),
                ('category_id', models.CharField(blank=True, max_length=500, null=True)),
                ('product_name', models.CharField(blank=True, max_length=500, null=True)),
                ('product_description', models.CharField(blank=True, max_length=500, null=True)),
                ('price', models.CharField(blank=True, max_length=500, null=True)),
                ('stock', models.CharField(blank=True, max_length=500, null=True)),
                ('product_weight', models.CharField(blank=True, max_length=500, null=True)),
                ('ship_out_in', models.CharField(blank=True, max_length=500, null=True)),
                ('parent_sku_reference_no', models.CharField(blank=True, max_length=500, null=True)),
                ('variation1_id', models.CharField(blank=True, max_length=500, null=True)),
                ('variation2_id', models.CharField(blank=True, max_length=500, null=True)),
                ('variation3_id', models.CharField(blank=True, max_length=500, null=True)),
                ('variation4_id', models.CharField(blank=True, max_length=500, null=True)),
                ('variation5_id', models.CharField(blank=True, max_length=500, null=True)),
                ('variation6_id', models.CharField(blank=True, max_length=500, null=True)),
                ('variation7_id', models.CharField(blank=True, max_length=500, null=True)),
                ('image1', models.CharField(blank=True, max_length=500, null=True)),
                ('image2', models.CharField(blank=True, max_length=500, null=True)),
                ('image3', models.CharField(blank=True, max_length=500, null=True)),
                ('image4', models.CharField(blank=True, max_length=500, null=True)),
                ('image5', models.CharField(blank=True, max_length=500, null=True)),
                ('image6', models.CharField(blank=True, max_length=500, null=True)),
                ('image7', models.CharField(blank=True, max_length=500, null=True)),
                ('other_logistics_provider_setting', models.CharField(blank=True, max_length=500, null=True)),
                ('other_logistics_provider_fee', models.CharField(blank=True, max_length=500, null=True)),
                ('order', modelcluster.fields.ParentalKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='product.Order')),
            ],
        ),
    ]
