# Generated by Django 2.0.2 on 2019-07-11 07:43

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_product_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total', models.CharField(blank=True, max_length=500, null=True)),
                ('status', models.CharField(blank=True, max_length=500, null=True)),
                ('countdown', models.CharField(blank=True, max_length=500, null=True)),
                ('shipping_channel', models.CharField(blank=True, max_length=500, null=True)),
                ('creation_date', models.CharField(blank=True, max_length=500, null=True)),
                ('paid_date', models.CharField(blank=True, max_length=500, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='product',
            name='order',
            field=modelcluster.fields.ParentalKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='product.Order'),
        ),
    ]
