# Generated by Django 2.0.13 on 2019-09-29 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_orderstatus'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderedproduct',
            name='cover_image_url',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='orderedproduct',
            name='product_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='orderedproduct',
            name='product_name',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='orderedproduct',
            name='product_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=100, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='orderedproduct',
            name='variation_image_url',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='orderedproduct',
            name='variation_name',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
