# Generated by Django 2.0.2 on 2019-07-29 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_auto_20190729_2020'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='unpublished',
            field=models.BooleanField(),
        ),
    ]
