# Generated by Django 2.0.13 on 2019-07-19 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_auto_20190719_1654'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='live',
            field=models.BooleanField(default=False),
        ),
    ]
