# Generated by Django 2.0.13 on 2019-10-01 05:12

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_drop_orders'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('order_reference_number', models.TextField(blank=True, primary_key=True, serialize=False)),
                ('total', models.CharField(blank=True, max_length=500, null=True)),
                ('status', models.CharField(blank=True, default='UNPAID', max_length=500, null=True)),
                ('status_changed_on', models.DateField(blank=True, default=datetime.datetime.now, null=True)),
                ('countdown', models.CharField(blank=True, max_length=500, null=True)),
                ('shipping_channel', models.CharField(blank=True, max_length=500, null=True)),
                ('creation_date', models.CharField(blank=True, max_length=500, null=True)),
                ('paid_date', models.CharField(blank=True, max_length=500, null=True)),
                ('shipping_address', models.TextField(blank=True, null=True)),
                ('pickup_address', models.TextField(blank=True, null=True)),
                ('user_id', models.CharField(blank=True, max_length=500, null=True)),
                ('username', models.CharField(blank=True, max_length=500, null=True)),
                ('additional_info', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='OrderedProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(blank=True, null=True)),
                ('product_price', models.DecimalField(blank=True, decimal_places=2, max_digits=100, max_length=500, null=True)),
                ('product_name', models.CharField(blank=True, max_length=500, null=True)),
                ('product_description', models.TextField(blank=True, null=True)),
                ('cover_image_url', models.TextField(blank=True, null=True)),
                ('variation_name', models.CharField(blank=True, max_length=500, null=True)),
                ('variation_image_url', models.TextField(blank=True, null=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.Order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.Product')),
                ('variation', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='product.Variations')),
            ],
        ),
        migrations.CreateModel(
            name='OrderStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(blank=True, default='UNPAID', max_length=500, null=True)),
                ('status_changed_on', models.DateField(blank=True, default=datetime.datetime.now, null=True)),
                ('additional_info', models.TextField(blank=True, null=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.Order')),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='products',
            field=models.ManyToManyField(through='product.OrderedProduct', to='product.Product'),
        ),
    ]
