# Generated by Django 2.0.13 on 2019-10-04 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0008_auto_20191003_1547'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='courier',
            field=models.CharField(blank=True, default='UNPAID', max_length=500, null=True),
        ),
    ]
