# Generated by Django 2.0.13 on 2019-07-19 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0008_product_live'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='suspended',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='unlisted',
            field=models.BooleanField(default=False),
        ),
    ]
