# Generated by Django 2.0.2 on 2019-07-29 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0008_auto_20190729_2131'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='unpublished',
            field=models.BooleanField(default=False),
        ),
    ]
