# Generated by Django 2.0.13 on 2019-10-04 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0009_order_courier'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='courier',
            field=models.CharField(blank=True, default='LOGISTIKUS', max_length=500, null=True),
        ),
    ]
