# Generated by Django 2.0.13 on 2019-08-01 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0010_errors'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_condition',
            field=models.CharField(blank=True, choices=[('N', 'New'), ('U', 'Used')], default=('N', 'New'), max_length=500, null=True),
        ),
    ]
