# Generated by Django 2.0.13 on 2019-07-26 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0010_productimportpage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='image1',
        ),
        migrations.RemoveField(
            model_name='product',
            name='image2',
        ),
        migrations.RemoveField(
            model_name='product',
            name='image3',
        ),
        migrations.RemoveField(
            model_name='product',
            name='image4',
        ),
        migrations.RemoveField(
            model_name='product',
            name='image5',
        ),
        migrations.RemoveField(
            model_name='product',
            name='image6',
        ),
        migrations.RemoveField(
            model_name='product',
            name='image7',
        ),
        migrations.RemoveField(
            model_name='product',
            name='variation1_id',
        ),
        migrations.RemoveField(
            model_name='product',
            name='variation2_id',
        ),
        migrations.RemoveField(
            model_name='product',
            name='variation3_id',
        ),
        migrations.RemoveField(
            model_name='product',
            name='variation4_id',
        ),
        migrations.RemoveField(
            model_name='product',
            name='variation5_id',
        ),
        migrations.RemoveField(
            model_name='product',
            name='variation6_id',
        ),
        migrations.RemoveField(
            model_name='product',
            name='variation7_id',
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='stock',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
