# Generated by Django 2.0.13 on 2019-10-19 14:01

import datetime
from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0012_auto_20191014_1500'),
    ]

    operations = [
        migrations.CreateModel(
            name='Courier',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('courier_name', models.CharField(blank=True, max_length=500, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='OrderCourier',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(blank=True, max_length=500, null=True)),
                ('status_changed_on', models.DateField(blank=True, default=datetime.datetime.now, null=True)),
                ('status_info', models.CharField(blank=True, max_length=500, null=True)),
                ('courier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.Courier')),
            ],
        ),
        migrations.AlterField(
            model_name='order',
            name='courier',
            field=models.ForeignKey(blank=True, max_length=500, null=True, on_delete=django.db.models.deletion.CASCADE, to='product.OrderCourier'),
        ),
        migrations.AddField(
            model_name='ordercourier',
            name='order_courier',
            field=modelcluster.fields.ParentalKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ordercourier', to='product.Order'),
        ),
    ]
