# Generated by Django 2.0.13 on 2019-08-01 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0013_category_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='shopee_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
