# Generated by Django 2.0.13 on 2019-10-23 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0013_auto_20191019_2201'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(blank=True, default='FOR_SHIPPING', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='orderstatus',
            name='status',
            field=models.CharField(blank=True, default='FOR_SHIPPING', max_length=500, null=True),
        ),
    ]
