# Generated by Django 2.0.13 on 2019-10-23 06:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0014_auto_20191023_0632'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status_changed_on',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now, null=True),
        ),
    ]
