# Generated by Django 2.0.13 on 2019-07-26 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0014_variations_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='variations',
            name='image_url',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
    ]
