# Generated by Django 2.0.13 on 2019-08-01 08:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0015_auto_20190801_1638'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='shopee_id',
            new_name='unique_id',
        ),
    ]
