# Generated by Django 2.0.13 on 2019-10-24 02:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0015_auto_20191023_0634'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordercourier',
            name='status_changed_on',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now, null=True),
        ),
        migrations.AlterField(
            model_name='orderstatus',
            name='status_changed_on',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now, null=True),
        ),
    ]
