# Generated by Django 2.0.13 on 2019-08-06 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0017_auto_20190805_1605'),
    ]

    operations = [
        migrations.AlterField(
            model_name='variations',
            name='image_upload',
            field=models.ImageField(blank=True, help_text='Optional: If you want to upload a new image. This will replace the image in the URL provided when bulk upload is performed.', null=True, upload_to=''),
        ),
    ]
