# Generated by Django 2.0.13 on 2019-08-06 08:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0018_auto_20190806_1637'),
    ]

    operations = [
        migrations.AlterField(
            model_name='variations',
            name='image_upload',
            field=models.ForeignKey(blank=True, help_text='Optional: If you want to upload a new image. This will replace the image in the URL provided when bulk upload is performed.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image'),
        ),
    ]
