# Generated by Django 2.0.13 on 2019-08-14 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0024_product_product_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='variations',
            name='image_url_from_upload',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_height',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_length',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_price',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_width',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='stock_sum',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
