# Generated by Django 2.0.13 on 2019-08-14 07:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        ('product', '0026_errors_profile_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='errors',
            name='profile_id',
        ),
        migrations.AddField(
            model_name='errors',
            name='profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='users.Profile'),
        ),
    ]
