# Generated by Django 2.0.13 on 2019-08-14 17:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0027_auto_20190814_1539'),
        ('product', '0025_auto_20190814_0755'),
    ]

    operations = [
    ]
