# Generated by Django 2.0.13 on 2019-08-19 08:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0028_merge_20190814_1731'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='errors',
            name='profile',
        ),
    ]
