# Generated by Django 2.0.13 on 2019-08-19 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0029_remove_errors_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_stock',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
