# Generated by Django 2.0.13 on 2019-08-29 08:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0030_product_product_stock'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='product_condition',
        ),
    ]
