# Generated by Django 2.0.13 on 2019-08-29 08:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0031_remove_product_product_condition'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_sale_date_end',
            field=models.DateField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='product',
            name='product_sale_date_start',
            field=models.DateField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='product',
            name='product_sale_price',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='product_sale_time_end',
            field=models.TimeField(blank=True, default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='product',
            name='product_sale_time_start',
            field=models.TimeField(blank=True, default=datetime.datetime.now),
        ),
    ]
