# Generated by Django 2.0.13 on 2019-09-02 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0036_product_product_brand'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='id',
        ),
        migrations.AlterField(
            model_name='category',
            name='unique_id',
            field=models.IntegerField(default=111, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
