# Generated by Django 2.0.13 on 2019-09-03 15:14

from django.db import migrations
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0037_auto_20190902_1633'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='order',
            field=modelcluster.fields.ParentalKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='product.Order'),
        ),
    ]
