# Generated by Django 2.0.13 on 2019-09-04 03:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_address_index'),
        ('product', '0039_auto_20190903_2322'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='users.Profile'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(blank=True, choices=[('U', 'Unpaid'), ('S', 'To Ship'), ('H', 'Shipping'), ('C', 'Completed'), ('L', 'Cancellation'), ('R', 'Return/Refund')], default=('U', 'Unpaid'), max_length=500, null=True),
        ),
    ]
