# Generated by Django 2.0.13 on 2019-09-08 11:57

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0040_auto_20190904_1126'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='live',
        ),
        migrations.RemoveField(
            model_name='product',
            name='other_logistics_provider_fee',
        ),
        migrations.RemoveField(
            model_name='product',
            name='other_logistics_provider_setting',
        ),
        migrations.RemoveField(
            model_name='product',
            name='product_sale_date_end',
        ),
        migrations.RemoveField(
            model_name='product',
            name='product_sale_date_start',
        ),
        migrations.RemoveField(
            model_name='product',
            name='product_sale_price',
        ),
        migrations.RemoveField(
            model_name='product',
            name='product_sale_time_end',
        ),
        migrations.RemoveField(
            model_name='product',
            name='product_sale_time_start',
        ),
        migrations.RemoveField(
            model_name='product',
            name='product_stock',
        ),
        migrations.RemoveField(
            model_name='product',
            name='suspended',
        ),
        migrations.RemoveField(
            model_name='product',
            name='unlisted',
        ),
        migrations.RemoveField(
            model_name='product',
            name='unpublished',
        ),
        migrations.AddField(
            model_name='product',
            name='cover_image_url',
            field=models.CharField(blank=True, help_text='Cover photo must have a white background', max_length=2000, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='product_status',
            field=models.CharField(blank=True, default='UNPUBLISHED', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='status_changed_on',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='product.Category'),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_height',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_length',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=100, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_weight',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_width',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='ship_out_in',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
