# Generated by Django 2.0.13 on 2019-09-08 12:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20190908_1157'),
        ('product', '0042_productimage'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProductImage',
            new_name='Image',
        ),
    ]
