# Generated by Django 2.0.2 on 2019-09-10 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0043_auto_20190908_1235'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(blank=True, default='UNPAID', max_length=500, null=True),
        ),
    ]
