# Generated by Django 2.0.13 on 2019-09-11 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0044_auto_20190910_1805'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='cover_image',
            field=models.ImageField(blank=True, help_text='Optional: If you want to upload a new image. This will replace the image in the URL provided when bulk upload is performed.', null=True, upload_to='original_images'),
        ),
        migrations.AddField(
            model_name='product',
            name='image1',
            field=models.ImageField(blank=True, help_text='Optional: If you want to upload a new image. This will replace the image in the URL provided when bulk upload is performed.', null=True, upload_to='original_images'),
        ),
        migrations.AddField(
            model_name='product',
            name='image1_url',
            field=models.CharField(blank=True, help_text='Photo must have a white background', max_length=2000, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='image2',
            field=models.ImageField(blank=True, help_text='Optional: If you want to upload a new image. This will replace the image in the URL provided when bulk upload is performed.', null=True, upload_to='original_images'),
        ),
        migrations.AddField(
            model_name='product',
            name='image2_url',
            field=models.CharField(blank=True, help_text='Photo must have a white background', max_length=2000, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='image3',
            field=models.ImageField(blank=True, help_text='Optional: If you want to upload a new image. This will replace the image in the URL provided when bulk upload is performed.', null=True, upload_to='original_images'),
        ),
        migrations.AddField(
            model_name='product',
            name='image3_url',
            field=models.CharField(blank=True, help_text='Photo must have a white background', max_length=2000, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='image4',
            field=models.ImageField(blank=True, help_text='Optional: If you want to upload a new image. This will replace the image in the URL provided when bulk upload is performed.', null=True, upload_to='original_images'),
        ),
        migrations.AddField(
            model_name='product',
            name='image4_url',
            field=models.CharField(blank=True, help_text='Photo must have a white background', max_length=2000, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='image5',
            field=models.ImageField(blank=True, help_text='Optional: If you want to upload a new image. This will replace the image in the URL provided when bulk upload is performed.', null=True, upload_to='original_images'),
        ),
        migrations.AddField(
            model_name='product',
            name='image5_url',
            field=models.CharField(blank=True, help_text='Photo must have a white background', max_length=2000, null=True),
        ),
    ]
