# Generated by Django 2.0.13 on 2019-09-15 08:09

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20190915_0809'),
        ('product', '0045_auto_20190911_1517'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_sale_price', models.IntegerField(blank=True, default=None, null=True)),
                ('product_sale_date_start', models.DateField(blank=True, default=datetime.datetime.now, null=True)),
                ('product_sale_date_end', models.DateField(blank=True, default=datetime.datetime.now, null=True)),
                ('product_sale_time_start', models.TimeField(blank=True, default=datetime.datetime.now, null=True)),
                ('product_sale_time_end', models.TimeField(blank=True, default=datetime.datetime.now, null=True)),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='product.Product')),
                ('variation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='product.Variations')),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='pickup_address',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='users.Address'),
        ),
        migrations.AddField(
            model_name='order',
            name='shipping_address',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='users.Address'),
        ),
        migrations.AddField(
            model_name='order',
            name='status_changed_on',
            field=models.DateField(blank=True, default=datetime.datetime.now, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='user_id',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='username',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
