# Generated by Django 2.0.13 on 2019-09-15 12:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0046_auto_20190915_0809'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='pickup_address',
        ),
        migrations.RemoveField(
            model_name='order',
            name='shipping_address',
        ),
        migrations.RemoveField(
            model_name='order',
            name='user_id',
        ),
        migrations.RemoveField(
            model_name='order',
            name='username',
        ),
    ]
