# Generated by Django 2.0.13 on 2019-09-15 13:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0048_auto_20190915_1217'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='products',
        ),
    ]
