# Generated by Django 2.0.13 on 2019-10-03 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('product', '0008_auto_20191003_1547'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=500, null=True)),
                ('categories', models.ManyToManyField(to='product.Category')),
                ('products', models.ManyToManyField(to='product.Product')),
            ],
        ),
    ]
