# Generated by Django 2.0.13 on 2019-07-19 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sign_up', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='signuppage',
            name='agreement_message',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
    ]
