# Generated by Django 2.0.13 on 2019-07-19 07:34

from django.db import migrations
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('sign_up', '0002_signuppage_agreement_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signuppage',
            name='agreement_message',
            field=wagtail.core.fields.RichTextField(blank=True, null=True),
        ),
    ]
