# Generated by Django 2.0.2 on 2019-07-11 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total', models.CharField(blank=True, max_length=500, null=True)),
                ('status', models.CharField(blank=True, max_length=500, null=True)),
                ('countdown', models.CharField(blank=True, max_length=500, null=True)),
                ('shipping_channel', models.CharField(blank=True, max_length=500, null=True)),
                ('creation_date', models.CharField(blank=True, max_length=500, null=True)),
                ('paid_date', models.CharField(blank=True, max_length=500, null=True)),
            ],
        ),
    ]
