# Generated by Django 2.0.2 on 2019-07-11 07:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_auto_20190711_1543'),
        ('sales', '0002_order'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Order',
        ),
    ]
